name: Build and Publish to private repository web
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
      - name: login to registry
        with:
          login-server: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build ./web/ -t ${{ secrets.REGISTRY_HOST }}/web:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_HOST }}/web:${{ github.sha }}
